In [20]:
import pandas as pd
import numpy as np
df = pd.read_csv ('ML_assignment02_dataset_2021.csv')
def del_duplicate(df):
    df=df.drop_duplicates()
    df.to_csv('del_duplicate.csv')
    return df
def fill_values(df):
    df=df.replace(0, np.nan)
    df = df.fillna(df.groupby(df.columns[3]).transform('mean'))
    df=round(df,2)
    df.to_csv('Missing_values.csv')
    return df
def transform_nominal(df):
    df = pd.concat([df, pd.get_dummies(df[df.columns[0]],df.drop(df.columns[0],inplace=True, axis=1))], axis=1)
    df.to_csv('transform_nominal.csv')
    return df
def normalise_minmax(df):
    result=df
    for col_name in df.columns[1:2]:
        max_value = df[col_name].max()
        min_value = df[col_name].min()
        result[col_name] = (df[col_name] - min_value) / (max_value - min_value)
    df=round(df,2)
    df.to_csv('normalise_minmax.csv')
    return df

In [21]:
del_duplicate(df)

    Colour  Radius (cm)  Weight (grams) Fruit (class)
0    Green          4.3             122          Pear
1    Green          4.6             152          Pear
2    Green          3.1              85         Apple
3    Green          3.6             173          Pear
4    Green          2.5              65         Lemon
5    Green          2.5              70         Apple
6    Green          2.7              73         Apple
7    Green          4.5             110          Pear
8    Green          2.5              86         Apple
9    Green          2.4              68         Lemon
10   Green          4.2             126          Pear
11     Red          3.7             101         Apple
12     Red          3.7             100         Apple
13     Red          3.4              80         Apple
14  Yellow          3.2              79         Apple
15  Yellow          3.1              69         Lemon
16  Yellow          2.1              64         Apple
17  Yellow          2.6              58         Lemon
18  Yellow          2.1              40         Lemon
19  Yellow          2.3              60         Lemon
20  Yellow          4.2             105          Pear
22  Yellow          3.2              64         Lemon
23  Yellow          2.9              53         Lemon
24  Yellow          4.1             135          Pear
25  Yellow          5.2             142          Pear
27  Yellow          0.0             137          Pear
28  Yellow          3.0              98         Apple
29  Yellow          2.4               0         Lemon
30  Yellow          4.1              56         Lemon
31  Yellow          4.1              80         Apple
32  Yellow          5.2             141          Pear
33  Yellow          0.0             135          Pear
34   Green          2.5               0         Apple

In [22]:
fill_values(df)

/var/folders/kg/8jhtm2gx4z1gz4877775tn980000gn/T/ipykernel_95157/1428696310.py:10: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the transforming function.
  df = df.fillna(df.groupby(df.columns[3]).transform('mean'))

    Colour  Radius (cm)  Weight (grams) Fruit (class)
0    Green         4.30          122.00          Pear
1    Green         4.60          152.00          Pear
2    Green         3.10           85.00         Apple
3    Green         3.60          173.00          Pear
4    Green         2.50           65.00         Lemon
5    Green         2.50           70.00         Apple
6    Green         2.70           73.00         Apple
7    Green         4.50          110.00          Pear
8    Green         2.50           86.00         Apple
9    Green         2.40           68.00         Lemon
10   Green         4.20          126.00          Pear
11     Red         3.70          101.00         Apple
12     Red         3.70          100.00         Apple
13     Red         3.40           80.00         Apple
14  Yellow         3.20           79.00         Apple
15  Yellow         3.10           69.00         Lemon
16  Yellow         2.10           64.00         Apple
17  Yellow         2.60           58.00         Lemon
18  Yellow         2.10           40.00         Lemon
19  Yellow         2.30           60.00         Lemon
20  Yellow         4.20          105.00          Pear
21  Yellow         2.10           40.00         Lemon
22  Yellow         3.20           64.00         Lemon
23  Yellow         2.90           53.00         Lemon
24  Yellow         4.10          135.00          Pear
25  Yellow         5.20          142.00          Pear
26  Yellow         2.30           60.00         Lemon
27  Yellow         4.43          137.00          Pear
28  Yellow         3.00           98.00         Apple
29  Yellow         2.40           57.55         Lemon
30  Yellow         4.10           56.00         Lemon
31  Yellow         4.10           80.00         Apple
32  Yellow         5.20          141.00          Pear
33  Yellow         4.43          135.00          Pear
34   Green         2.50           83.27         Apple

In [23]:
transform_nominal(df)

    Radius (cm)  Weight (grams) Fruit (class)  Green  Red  Yellow
0           4.3             122          Pear      1    0       0
1           4.6             152          Pear      1    0       0
2           3.1              85         Apple      1    0       0
3           3.6             173          Pear      1    0       0
4           2.5              65         Lemon      1    0       0
5           2.5              70         Apple      1    0       0
6           2.7              73         Apple      1    0       0
7           4.5             110          Pear      1    0       0
8           2.5              86         Apple      1    0       0
9           2.4              68         Lemon      1    0       0
10          4.2             126          Pear      1    0       0
11          3.7             101         Apple      0    1       0
12          3.7             100         Apple      0    1       0
13          3.4              80         Apple      0    1       0
14          3.2              79         Apple      0    0       1
15          3.1              69         Lemon      0    0       1
16          2.1              64         Apple      0    0       1
17          2.6              58         Lemon      0    0       1
18          2.1              40         Lemon      0    0       1
19          2.3              60         Lemon      0    0       1
20          4.2             105          Pear      0    0       1
21          2.1              40         Lemon      0    0       1
22          3.2              64         Lemon      0    0       1
23          2.9              53         Lemon      0    0       1
24          4.1             135          Pear      0    0       1
25          5.2             142          Pear      0    0       1
26          2.3              60         Lemon      0    0       1
27          0.0             137          Pear      0    0       1
28          3.0              98         Apple      0    0       1
29          2.4               0         Lemon      0    0       1
30          4.1              56         Lemon      0    0       1
31          4.1              80         Apple      0    0       1
32          5.2             141          Pear      0    0       1
33          0.0             135          Pear      0    0       1
34          2.5               0         Apple      1    0       0

In [24]:
normalise_minmax(df)

    Radius (cm)  Weight (grams) Fruit (class)
0           4.3            0.71          Pear
1           4.6            0.88          Pear
2           3.1            0.49         Apple
3           3.6            1.00          Pear
4           2.5            0.38         Lemon
5           2.5            0.40         Apple
6           2.7            0.42         Apple
7           4.5            0.64          Pear
8           2.5            0.50         Apple
9           2.4            0.39         Lemon
10          4.2            0.73          Pear
11          3.7            0.58         Apple
12          3.7            0.58         Apple
13          3.4            0.46         Apple
14          3.2            0.46         Apple
15          3.1            0.40         Lemon
16          2.1            0.37         Apple
17          2.6            0.34         Lemon
18          2.1            0.23         Lemon
19          2.3            0.35         Lemon
20          4.2            0.61          Pear
21          2.1            0.23         Lemon
22          3.2            0.37         Lemon
23          2.9            0.31         Lemon
24          4.1            0.78          Pear
25          5.2            0.82          Pear
26          2.3            0.35         Lemon
27          0.0            0.79          Pear
28          3.0            0.57         Apple
29          2.4            0.00         Lemon
30          4.1            0.32         Lemon
31          4.1            0.46         Apple
32          5.2            0.82          Pear
33          0.0            0.78          Pear
34          2.5            0.00         Apple